config/routes.rb
Registration::Application.routes.draw do
  resources :members

end

app/models/member.rb
class Member < ActiveRecord::Base
  validates_presence_of :name, :affiliation, :email => " - mandatory field"
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.xml
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/new
  # GET /members/new.xml
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.xml
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to(@member, :notice => 'You have successfully registered for the conference!') }
        format.xml  { render :xml => @member, :status => :created, :location => @member }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en-US" xml:lang="en-US">  
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>  
  <title>Workshop on Information Science and Related Technologies | Registration</title>
  <link href="http://webcore.unm.edu/v1/images/unm.ico" rel="shortcut icon"/>
  <link href="http://webcore.unm.edu/v1/css/styles.php" media="screen" rel="stylesheet" type="text/css"/>
  <link href="http://webcore.unm.edu/v1/css/styles.php?media=print" media="print" rel="stylesheet" type="text/css"/>
  <link href="http://www.unm.edu/common/css/site.css" media="screen" rel="stylesheet" type="text/css"/>
  
    <!--[if lt IE 7]>
      <link href="http://webcore.unm.edu/v1/css/ie.css" rel="stylesheet" type="text/css" media="screen" />
    <![endif]-->
  
  <script src="http://webcore.unm.edu/v1/javascript/jquery.min.js" type="text/javascript"></script>
  
  <script src="http://webcore.unm.edu/v1/javascript/unm_scripts.php" type="text/javascript"></script>
  
  <meta content="3 Column" name="layout"/>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<body>
  <div id="page">
    <div id="dept_header">
      <div id="dept_logo"><img src="images/logo.jpg" height=176 width=956 /></div>
        <ul id="dropnav">
         <li><a class="" href="index.html">Home</a></li>
         
         <li><a class=" submenu" href="index.html">About the Workshop</a>
              <ul>
                <li><a href="program.html">Program</a></li>
                <!-- <li><a href="speakers.html">Speakers</a></li> -->
                <li><a href="sponsors.html">Sponsors</a></li>
              </ul></li>
         
          <li><a class="" href="travel.html">Travel & Location</a></li>
          <li><a class="current" href="registration.html">Registration</a></li>
          
          <li><a class=" submenu" href="media.html">Media</a>
            <ul>
              <li><a href="media.html">Video</a></li>
              <li><a href="media.html">Live Feeds</a></li>
              <li><a href="media.html">Pictures</a></li>
            </ul></li>
          
          <li><a href="contact.html">Contact Us</a></li>
        </ul>    
      </div>
  
  <div class="col1" id="container">
    
    <div id="content_top">
      <div class="content">
        <ul id="unm_breadcrumbs">
          <li class="unm_home"><a href="index.html">Home</a></li>
          <li><span class="breadcrumb-div">»</span>Registration</li>
        </ul>
        
      </div>
    </div>
 
    <div id="content">
      <div class="content">

        <h1 align="center">Workshop Registration</h1>
        <br>
          
        <%= yield %>
        </div>
    </div>

  </div>
  
  <div id="footer">
    <div class="content">
    </div>
  </div>
  
</div>
</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>Due to <%= pluralize(@member.errors.count, "error") %>, the registration cannot be completed. Please try again!</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :affiliation %><br />
    <%= f.text_field :affiliation %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :nickname %> (name as it should appear on your Name Tag)<br />
    <%= f.text_field :nickname %>
  </div>
  <div class="actions">

    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Affiliation</th>
    <th>Email</th>
    <th>Nickname</th>
    <th></th>
    <!--<th></th>-->
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.name %></td>
    <td><%= member.affiliation %></td>
    <td><%= member.email %></td>
    <td><%= member.nickname %></td>
    <td><%= link_to 'Show', member %></td>
    <!--<td><%= link_to 'Edit', edit_member_path(member) %></td>-->
    <td><%= link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<p align="justify">
  Please enter the following details as accurately as possible. If you have questions, please email <a href="mailto:US-Spain@ece.unm.edu">US-Spain@ece.unm.edu</a>.
</p>

<%= render 'form' %>

<!--<%= link_to 'Back', members_path %>-->

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Affiliation:</b>
  <%= @member.affiliation %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Nickname:</b>
  <%= @member.nickname %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>